export default function PrintColophon() {
	return (
		<div id="print-colophon" aria-hidden="true">
			{'Generated by '}
			<a href={window.location.href}>{window.location.href}</a>
			{' on '}
			{new Date().toLocaleString('en-GB', {
				dateStyle: 'long',
				timeStyle: 'medium',
			})}
		</div>
	);
}
